export const mockData = [
  {
    name: "545-PREMIUM-LEATHER-JACKET-BLACK",
    color: "Black",
    price: "89.99",
    details: [
      "knitted Rugby Jacket",
      "Multilayered Acrylic/Nylon Yarn Made For Comfort",
      "All Over Mosaic",
    ],
    delivery: "Ships Within 3 business days",
    sold: false,
    front_image: "/545/545_PREMIUM_LEATHER_JACKET_BLACK_FRONT.webp",
    image_p1: "/545/545_PREMIUM_LEATHER_JACKET_BLACK_P1.webp",
    image_p2: "/545/545_PREMIUM_LEATHER_JACKET_BLACK_P2.webp",
    image_p3: "/545/545_PREMIUM_LEATHER_JACKET_BLACK_P3.webp",
  },
  {
    name: "545-PREMIUM-LEATHER-JACKET-BROWN",
    color: "Brown",
    price: "89.99",
    details: [
      "knitted Rugby Jacket",
      "Multilayered Acrylic/Nylon Yarn Made For Comfort",
      "All Over Mosaic",
    ],
    delivery: "Ships Within 3 business days",
    sold: false,
    front_image: "/545/545_PREMIUM_LEATHER_JACKET_BROWN_FRONT.webp",
    image_p1: "/545/545_PREMIUM_LEATHER_JACKET_BROWN_P1.webp",
    image_p2: "/545/545_PREMIUM_LEATHER_JACKET_BROWN_P2.webp",
    image_p3: "/545/545_PREMIUM_LEATHER_JACKET_BROWN_P3.webp",
  },
  {
    name: "545-PREMIUM-SWEDE-JACKET-ASH",
    color: "Ash",
    price: "89.99",
    details: [
      "knitted Rugby Jacket",
      "Multilayered Acrylic/Nylon Yarn Made For Comfort",
      "All Over Mosaic",
    ],
    delivery: "Ships Within 3 business days",
    sold: false,
    front_image: "/545/545_PREMIUM_SWEDE_JACKET_ASH_FRONT.webp",
    image_p1: "//545/545_PREMIUM_SWEDE_JACKET_ASH_P1.webp",
    image_p2: "/545/545_PREMIUM_SWEDE_JACKET_ASH_P2.webp",
    image_p3: "/545/545_PREMIUM_SWEDE_JACKET_ASH_P3.webp",
  },
  {
    name: "545-PREMIUM-SWEDE-JACKET-BROWN",
    color: "Brown",
    price: "89.99",
    details: [
      "knitted Rugby Jacket",
      "Multilayered Acrylic/Nylon Yarn Made For Comfort",
      "All Over Mosaic",
    ],
    delivery: "Ships Within 3 business days",
    sold: false,
    front_image: "/545/545_PREMIUM_SWEDE_JACKET_BROWN_FRONT.webp",
    image_p1: "/545/545_PREMIUM_SWEDE_JACKET_BROWN_P1.webp",
    image_p2: "/545/545_PREMIUM_SWEDE_JACKET_BROWN_P2.webp",
    image_p3: "/545/545_PREMIUM_SWEDE_JACKET_BROWN_P3.webp",
  },
  {
    name: "545-EVERYDAY-CARDIGAN-ASH",
    color: "Ash",
    price: "89.99",
    details: [
      "knitted Rugby Jacket",
      "Multilayered Acrylic/Nylon Yarn Made For Comfort",
      "All Over Mosaic",
    ],
    delivery: "Ships Within 3 business days",
    sold: false,
    front_image: "/545/545_EVERYDAY_CARDIGAN_ASH_FRONT.webp",
    image_p1: "/545/545_EVERYDAY_CARDIGAN_ASH_P1.webp",
    image_p2: "/545/545_EVERYDAY_CARDIGAN_ASH_P2.webp",
    image_p3: "/545/545_EVERYDAY_CARDIGAN_ASH_P3.webp",
  },
  {
    name: "545-EVERYDAY-CARDIGAN-BLACK",
    color: "Jet Black",
    price: "89.99",
    details: [
      "knitted Rugby Jacket",
      "Multilayered Acrylic/Nylon Yarn Made For Comfort",
      "All Over Mosaic",
    ],
    delivery: "Ships Within 3 business days",
    sold: false,
    front_image: "/545/545_EVERYDAY_CARDIGAN_BLACK_FRONT.webp",
    image_p1: "/545/545_EVERYDAY_CARDIGAN_BLACK_P1.webp",
    image_p2: "/545/545_EVERYDAY_CARDIGAN_BLACK_P2.webp",
    image_p3: "/545/545_EVERYDAY_CARDIGAN_BLACK_P3.webp",
  },
  {
    name: "545-EVERYDAY-CARDIGAN-CREAM",
    color: "Cream",
    price: "89.99",
    details: [
      "knitted Rugby Jacket",
      "Multilayered Acrylic/Nylon Yarn Made For Comfort",
      "All Over Mosaic",
    ],
    delivery: "Ships Within 3 business days",
    sold: false,
    front_image: "/545/545_EVERYDAY_CARDIGAN_CREAM_FRONT.webp",
    image_p1: "/545/545_EVERYDAY_CARDIGAN_CREAM_P1.webp",
    image_p2: "/545/545_EVERYDAY_CARDIGAN_CREAM_P2.webp",
    image_p3: "/545/545_EVERYDAY_CARDIGAN_CREAM_P3.webp",
  },
  {
    name: "545-EVERYDAY-CARDIGAN-GREEN",
    color: "Green",
    price: "89.99",
    details: [
      "knitted Rugby Jacket",
      "Multilayered Acrylic/Nylon Yarn Made For Comfort",
      "All Over Mosaic",
    ],
    delivery: "Ships Within 3 business days",
    sold: false,
    front_image: "/545/545_EVERYDAY_CARDIGAN_GREEN_FRONT.webp",
    image_p1: "/545/545_EVERYDAY_CARDIGAN_GREEN_P1.webp",
    image_p2: "/545/545_EVERYDAY_CARDIGAN_GREEN_P2.webp",
    image_p3: "/545/545_EVERYDAY_CARDIGAN_GREEN_P3.webp",
  },
];
