import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import QueryProvider from "@/providers/queryProvider";
import { CartProvider } from "../contexts/CartContext";
import ScrollToTop from "@/components/ui/scrollToTop";

export const metadata: Metadata = {
  title: "NEW",
  description: "Generated by create next app",
};

export const roboto = Roboto_Slab({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className={`antialiased bg-white scroll-smooth`}>
        <CartProvider>
          <QueryProvider>
            <Header />

            <main className="w-full">
              <ScrollToTop />
              {children}
            </main>
          </QueryProvider>
        </CartProvider>
      </body>
    </html>
  );
}
